/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import banco.BuscaBibliotecarioBanco;
import banco.Conexao;
import interfaces.Dependente;
import interfaces.Parente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bibliotecaria;

/**
 *
 * @author Marcelo Moreira
 */
public class BuscaBibliotecario extends javax.swing.JFrame {
    private Parente parent;
    private BuscaBibliotecarioBanco bb;
    private ArrayList<Bibliotecaria> resultado;

    /**
     * Creates new form BuscaBibliotecario
     */
    public BuscaBibliotecario() {
        initComponents();
    }

    public BuscaBibliotecario(Parente parent) {
        this();
        this.parent = parent;
        this.setIconImage(this.parent.getIcone());
        resultado = new ArrayList<>();
        bb = new BuscaBibliotecarioBanco(Conexao.getConexao());
        inicializarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbTipoBusca = new javax.swing.JComboBox<>();
        btnBuscar = new java.awt.Button();
        txtConteudoBuscar = new javax.swing.JTextField();
        lblConteudo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResultado = new javax.swing.JTable();
        btnSelecionar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Bibliotecário");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cbTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome", "CPF", "E-mail" }));
        cbTipoBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoBuscaItemStateChanged(evt);
            }
        });

        btnBuscar.setLabel("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtConteudoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConteudoBuscarKeyPressed(evt);
            }
        });

        lblConteudo.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConteudoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTipoBusca)
                        .addComponent(txtConteudoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblConteudo))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbResultado);

        btnSelecionar.setLabel("Selecionar >");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoBuscaItemStateChanged
        switch (cbTipoBusca.getSelectedIndex()) {
            case 0:
                lblConteudo.setText("ID:");
                break;
            case 1:
                lblConteudo.setText("Nome:");
                break;
            case 2:
                lblConteudo.setText("CPF:");
                break;
            case 3:
                lblConteudo.setText("E-mail:");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbTipoBuscaItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setEstadoAtivacao(true);
        restaurarTela();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtConteudoBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConteudoBuscarKeyPressed
        if(evt.getKeyCode() == 8){
            if(txtConteudoBuscar.getText().equals("")){
                inicializarTabela();
            }
        }
        
        if(evt.getKeyCode() == 10){
            buscar();
        }
    }//GEN-LAST:event_txtConteudoBuscarKeyPressed

    private void tbResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResultadoMouseClicked
        if(evt.getClickCount() == 2){
            selecionar();
        }
    }//GEN-LAST:event_tbResultadoMouseClicked

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        selecionar();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void selecionar(){
        try{
            String id_biblio  = tbResultado.getValueAt(tbResultado.getSelectedRow(), 0).toString();
            int id = Integer.parseInt(id_biblio);
            
            for(Bibliotecaria b : resultado){
                if(b.getId() == id){
                    ((Dependente) parent).setInformacaoDependente(b);
                    parent.setEstadoAtivacao(true);
                    this.dispose();
                    break;
                }
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro ao tentar converter o id para int!", "Erro na conversão", JOptionPane.ERROR_MESSAGE);
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Você precisa selecionar uma linha da tabela!", "Selecione uma linha", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buscar() {
        if (!txtConteudoBuscar.getText().equals("")) {
            resultado.clear();
            switch (cbTipoBusca.getSelectedIndex()) {
                case 0:
                    //ID
                    resultado = bb.buscarBibliotecaria(txtConteudoBuscar.getText(), 0);
                    break;
                case 1:
                    //Nome
                    resultado = bb.buscarBibliotecaria(txtConteudoBuscar.getText(), 1);
                    break;
                case 2:
                    //CPF
                    resultado = bb.buscarBibliotecaria(txtConteudoBuscar.getText(), 2);
                    break;
                case 3:
                    //Email
                    resultado = bb.buscarBibliotecaria(txtConteudoBuscar.getText(), 3);
                    break;
                default:
                    break;
            }

            DefaultTableModel dtbm = (DefaultTableModel) tbResultado.getModel();
            while (dtbm.getRowCount() > 0) {
                dtbm.removeRow(0);
            }

            int i = 0;

            for (Bibliotecaria b : resultado) {
                dtbm.addRow(new String[i]);
                tbResultado.setValueAt(b.getId(), i, 0);
                tbResultado.setValueAt(b.getNome(), i, 1);
                tbResultado.setValueAt(b.getCpf(), i, 2);
                tbResultado.setValueAt(b.getEmail(), i, 3);
                i++;
            }
        } else {
            txtConteudoBuscar.requestFocus();
            JOptionPane.showMessageDialog(null, "Preencha o campo de busca para prosseguir com a ação!", "Campo vazio", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void inicializarTabela() {
        resultado.clear();
        resultado = bb.listarBibliotecarios();
        
        DefaultTableModel dtbm = (DefaultTableModel) tbResultado.getModel();
        while (dtbm.getRowCount() > 0) {
            dtbm.removeRow(0);
        }

        int i = 0;

        for (Bibliotecaria b : resultado) {
            dtbm.addRow(new String[i]);
            tbResultado.setValueAt(b.getId(), i, 0);
            tbResultado.setValueAt(b.getNome(), i, 1);
            tbResultado.setValueAt(b.getCpf(), i, 2);
            tbResultado.setValueAt(b.getEmail(), i, 3);
            i++;
        }
    }

    private void restaurarTela() {
        txtConteudoBuscar.setText("");
        cbTipoBusca.setSelectedIndex(0);
        tbResultado.removeAll();
        resultado.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaBibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBuscar;
    private java.awt.Button btnSelecionar;
    private javax.swing.JComboBox<String> cbTipoBusca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConteudo;
    private javax.swing.JTable tbResultado;
    private javax.swing.JTextField txtConteudoBuscar;
    // End of variables declaration//GEN-END:variables
}
