/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import banco.Conexao;
import banco.Sistema;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import model.Bibliotecaria;




/**
 *
 * @author Gigo
 */
public class Principal extends javax.swing.JFrame {
    private Bibliotecaria bibliotecariaLogada;
    private Conexao conexao;
    private Login telaLogin;
    private TelaUsuario telaCadUsuario;
    private TelaLivro telaCadLivro;
    private TelaExemplar telaCadExemplar;
    private TelaEmprestimo telaEmprestimo;
    private Sistema sistema;
    

    public void setBibliotecariaLogada(Bibliotecaria bibliotecariaLogada) {
        this.bibliotecariaLogada = bibliotecariaLogada;
        txtIdBibliotecariaLogada.setText(String.valueOf(bibliotecariaLogada.getId()));
        txtNomeBibliotecariaLogada.setText(bibliotecariaLogada.getNome());
        if(bibliotecariaLogada.getTipo().equals("admin")){
            txtTipoBiblioLogada.setText("Administrador");
        }else if(bibliotecariaLogada.getTipo().equals("normal")){
            txtTipoBiblioLogada.setText("Normal");
        }
        liberarPrograma();
    }
    
    public Bibliotecaria getBibliotecarialogada(){
        return this.bibliotecariaLogada;
    }
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        URL url = this.getClass().getResource("images/logo.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        conexao = new Conexao();
        sistema = new Sistema(Conexao.getConexao());
        bloquearPrograma();
        telaLogin = new Login(this);
        
        
        telaCadUsuario = new TelaUsuario(this);
        telaCadLivro = new TelaLivro(this);
        telaCadExemplar = new TelaExemplar(this);
        telaEmprestimo = new TelaEmprestimo(this);
        
        try {
            Process p = Runtime.getRuntime().exec("C:\\xampp\\xampp_start.exe");
            if (p.exitValue() == 0) {
                System.out.println("Programa terminou normalmente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xampp não foi encontrado no diretório C:\\xampp", "Erro ao inicializar o xampp", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeBibliotecariaLogada = new java.awt.TextField();
        txtIdBibliotecariaLogada = new java.awt.TextField();
        txtStatusPrograma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipoBiblioLogada = new java.awt.TextField();
        dpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogoff = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuEmp = new javax.swing.JMenu();
        menuEmprestimo = new javax.swing.JMenuItem();
        menuLivro = new javax.swing.JMenu();
        menuNovoLivro = new javax.swing.JMenuItem();
        menuExemplar = new javax.swing.JMenu();
        menuNovoExemplar = new javax.swing.JMenuItem();
        menuUsu = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenuItem();
        menuBibliotecaria = new javax.swing.JMenu();
        menuBibliotecario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bibliotecário v1.0");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID:");

        txtNomeBibliotecariaLogada.setEditable(false);
        txtNomeBibliotecariaLogada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtIdBibliotecariaLogada.setEditable(false);
        txtIdBibliotecariaLogada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtStatusPrograma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtStatusPrograma.setForeground(new java.awt.Color(255, 0, 51));

        jLabel2.setText("Nome:");

        jLabel3.setText("Tipo:");

        txtTipoBiblioLogada.setEditable(false);
        txtTipoBiblioLogada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdBibliotecariaLogada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeBibliotecariaLogada, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoBiblioLogada, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(txtStatusPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdBibliotecariaLogada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeBibliotecariaLogada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatusPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipoBiblioLogada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        menuSistema.setText("Sistema");

        menuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuSistema.add(menuLogin);

        menuLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuLogoff.setText("Logoff");
        menuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoffActionPerformed(evt);
            }
        });
        menuSistema.add(menuLogoff);

        menuConfig.setText("Configurações");
        menuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigActionPerformed(evt);
            }
        });
        menuSistema.add(menuConfig);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuSair);

        jMenuBar1.add(menuSistema);

        menuEmp.setText("Empréstimo");

        menuEmprestimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuEmprestimo.setText("Empréstimo");
        menuEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmprestimoActionPerformed(evt);
            }
        });
        menuEmp.add(menuEmprestimo);

        jMenuBar1.add(menuEmp);

        menuLivro.setText("Livro");

        menuNovoLivro.setText("Livro");
        menuNovoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoLivroActionPerformed(evt);
            }
        });
        menuLivro.add(menuNovoLivro);

        jMenuBar1.add(menuLivro);

        menuExemplar.setText("Exemplar");

        menuNovoExemplar.setText("Exemplar");
        menuNovoExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoExemplarActionPerformed(evt);
            }
        });
        menuExemplar.add(menuNovoExemplar);

        jMenuBar1.add(menuExemplar);

        menuUsu.setText("Usuário");

        menuUsuario.setText("Usuário");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        menuUsu.add(menuUsuario);

        jMenuBar1.add(menuUsu);

        menuBibliotecaria.setText("Bibliotecário(a)");

        menuBibliotecario.setText("Bibliotecário(a)");
        menuBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBibliotecarioActionPerformed(evt);
            }
        });
        menuBibliotecaria.add(menuBibliotecario);

        jMenuBar1.add(menuBibliotecaria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoffActionPerformed
        bloquearPrograma();
        JOptionPane.showMessageDialog(null, "Sessão Encerrada!", "Sessão Encerrada", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_menuLogoffActionPerformed

    private void menuNovoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoLivroActionPerformed
        this.enable(false);
        telaCadLivro.setVisible(true);
    }//GEN-LAST:event_menuNovoLivroActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        this.enable(false);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_menuLoginActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Conexao.FecharConexao();
    }//GEN-LAST:event_formWindowClosing

    private void menuBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBibliotecarioActionPerformed
        Bibliotecario telaBiblio = new Bibliotecario(this);
        this.enable(false);
        telaBiblio.setVisible(true);
    }//GEN-LAST:event_menuBibliotecarioActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        
        this.enable(false);
        telaCadUsuario.setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuNovoExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoExemplarActionPerformed
        this.enable(false);
        telaCadExemplar.setVisible(true);
    }//GEN-LAST:event_menuNovoExemplarActionPerformed

    private void menuEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmprestimoActionPerformed
        this.enable(false);
        telaEmprestimo.setVisible(true);
    }//GEN-LAST:event_menuEmprestimoActionPerformed

    private void menuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigActionPerformed
        TelaConfig t = new TelaConfig(this);
        this.enable(false);
        t.setVisible(true);
    }//GEN-LAST:event_menuConfigActionPerformed

    private void bloquearPrograma(){
        menuEmp.setEnabled(false);
        menuLivro.setEnabled(false);
        menuExemplar.setEnabled(false);
        menuUsu.setEnabled(false);
        menuBibliotecaria.setEnabled(false);
        menuLogoff.setEnabled(false);
        menuConfig.setEnabled(false);
        menuLogin.setEnabled(true);
        bibliotecariaLogada = null;
        txtIdBibliotecariaLogada.setText("");
        txtNomeBibliotecariaLogada.setText("");
        txtTipoBiblioLogada.setText("");
        txtStatusPrograma.setText("Bloqueado!");
    }
    
    private void liberarPrograma(){
        menuEmp.setEnabled(true);
        menuLivro.setEnabled(true);
        menuExemplar.setEnabled(true);
        menuUsu.setEnabled(true);
        menuBibliotecaria.setEnabled(true);
        menuLogoff.setEnabled(true);
        menuLogin.setEnabled(false);
        if(bibliotecariaLogada.getTipo().equals("admin")){
            menuConfig.setEnabled(true);
        }else{
            menuConfig.setEnabled(false);
        }
        txtStatusPrograma.setText("Liberado!");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuBibliotecaria;
    private javax.swing.JMenuItem menuBibliotecario;
    private javax.swing.JMenuItem menuConfig;
    private javax.swing.JMenu menuEmp;
    private javax.swing.JMenuItem menuEmprestimo;
    private javax.swing.JMenu menuExemplar;
    private javax.swing.JMenu menuLivro;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogoff;
    private javax.swing.JMenuItem menuNovoExemplar;
    private javax.swing.JMenuItem menuNovoLivro;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuUsu;
    private javax.swing.JMenuItem menuUsuario;
    private java.awt.TextField txtIdBibliotecariaLogada;
    private java.awt.TextField txtNomeBibliotecariaLogada;
    private javax.swing.JLabel txtStatusPrograma;
    private java.awt.TextField txtTipoBiblioLogada;
    // End of variables declaration//GEN-END:variables
}
