/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import banco.UsuarioBanco;
import banco.Conexao;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Marcelo Moreira
 */
public class TelaUsuario extends javax.swing.JFrame {
    private Principal parent;
    private UsuarioBanco ub;
    private Usuario usuario;
    private String modo;
    
    public void setUsuario(Usuario b){
        usuario = b;
        txtID.setText(String.valueOf(b.getId()));
        txtNome.setText(b.getNome());
        txtCpf.setText(b.getCpf());
        txtEmail.setText(b.getEmail());
        modo = "buscado";
        camposBuscado();
        if(b.getTipo().equals("Aluno")){
            rbAluno.setSelected(true);
        }else if(b.getTipo().equals("Professor")){
            rbProfessor.setSelected(true);
        }
    }
    
    public TelaUsuario() {
        initComponents();
        ub = new UsuarioBanco(Conexao.getConexao());
    }
    
    public TelaUsuario(Principal parent){
        this();
        this.parent = parent;
        restaurarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        rbAluno = new javax.swing.JRadioButton();
        rbProfessor = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtSenhaConfirm = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnNovo = new java.awt.Button();
        btnCancelar = new java.awt.Button();
        btnConfirmar = new java.awt.Button();
        btnBuscar = new java.awt.Button();
        btnAtualizar = new java.awt.Button();
        btnExcluir = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuário");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("E-mail:");

        jLabel5.setText("Senha:");

        jLabel6.setText("Confirmação:");

        optGroupTipo.add(rbAluno);
        rbAluno.setText("Aluno");

        optGroupTipo.add(rbProfessor);
        rbProfessor.setText("Professor");

        txtSenhaConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaConfirmKeyPressed(evt);
            }
        });

        jLabel7.setText("ID:");

        txtID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtID.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenhaConfirm)
                    .addComponent(txtSenha)
                    .addComponent(txtEmail)
                    .addComponent(txtCpf)
                    .addComponent(txtNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(rbAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbProfessor))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAluno)
                    .addComponent(rbProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setLabel("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setLabel("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnBuscar.setLabel("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtualizar.setLabel("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setLabel("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAtualizar, btnBuscar, btnCancelar, btnConfirmar, btnExcluir, btnNovo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtualizar, btnBuscar, btnCancelar, btnConfirmar, btnExcluir, btnNovo});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        camposNovo();
        modo = "novo";
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.enable(true);
        restaurarTela();
    }//GEN-LAST:event_formWindowClosing

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Realmente deseja cancelar?", "Cancelar Operação", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            restaurarTela();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtSenhaConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaConfirmKeyPressed
        if(evt.getKeyCode() == 10){
            realizarAcao();
        }
    }//GEN-LAST:event_txtSenhaConfirmKeyPressed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        realizarAcao();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscaUsuario bb = new BuscaUsuario(this, null);
        this.enable(false);
        bb.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        modo = "atualizar";
        camposAtualizar();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o usuário?", "Excluir Usuário", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            excluir();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void excluir(){
        int id = Integer.parseInt(txtID.getText());
        boolean resul = ub.excluirUsuario(id);
        if(resul){
            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Exclusão efetuada", JOptionPane.INFORMATION_MESSAGE);
            restaurarTela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao tentar excluir o usuário!", "Erro na exclusão", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void realizarAcao(){
        if(modo.equals("novo")){
            cadastrar();
        }else if(modo.equals("atualizar")){
            atualizar();
        }
    }
    
    
    private void camposAtualizar(){
        txtCpf.setEditable(true);
        txtEmail.setEditable(true);
        txtNome.setEditable(true);
        txtSenha.setEditable(true);
        txtSenhaConfirm.setEditable(true);
        rbAluno.setEnabled(true);
        rbProfessor.setEnabled(true);
        btnAtualizar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnConfirmar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
        rbAluno.requestFocus();
    }
    
    private void atualizar(){
        if(!txtCpf.getText().equals("") && !txtEmail.getText().equals("") && !txtNome.getText().equals("") && (rbAluno.isSelected() || rbProfessor.isSelected())){
            if((!txtSenha.getText().equals("") && !txtSenhaConfirm.getText().equals("")) || (txtSenha.getText().equals("") && txtSenhaConfirm.getText().equals(""))){
                if(txtSenha.getText().equals(txtSenhaConfirm.getText())){
                    boolean resu = ub.atualizarUsuario(Integer.parseInt(txtID.getText()), txtNome.getText(), txtCpf.getText(), tipo(), txtEmail.getText(), txtSenha.getText());
                    if(resu){
                        JOptionPane.showMessageDialog(null, "Atualização de dados realizada com sucesso!", "Atualização efetuada", JOptionPane.INFORMATION_MESSAGE);
                        restaurarTela();
                    }else{
                        JOptionPane.showMessageDialog(null, "Erro ao tentar realizar a atualização dos dados!\nO email requisitado pode ja ter sido cadastrado no sistema.", "Atualização não efetuada", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "As senhas são incompatíveis!", "Senhas incompatíveis", JOptionPane.ERROR_MESSAGE);
                    txtSenha.requestFocus();
                }
            }else if((txtSenha.getText().equals("") && !txtSenhaConfirm.getText().equals("")) || (!txtSenha.getText().equals("") && txtSenhaConfirm.getText().equals(""))){
                JOptionPane.showMessageDialog(null, "Os dois campos de senha devem ser preenchidos!", "Campos vazios", JOptionPane.ERROR_MESSAGE);
                txtSenha.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para realizar a atualização, exceto os campos de senha!", "Campos vazios", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String tipo(){
        String tipo;
        if(rbAluno.isSelected()){
            tipo = "Aluno";
        }else if(rbProfessor.isSelected()){
            tipo = "Professor";
        }else{
            tipo = null;
        }
        return tipo;
    }
    
    private void cadastrar(){
        if(txtSenha.getText().equals(txtSenhaConfirm.getText())){
            if(!txtCpf.getText().equals("") && !txtEmail.getText().equals("") && !txtNome.getText().equals("") && !txtSenha.getText().equals("") && !txtSenhaConfirm.getText().equals("") && (rbAluno.isSelected() || rbProfessor.isSelected())){                
                int tipo = 0;
                if(rbProfessor.isSelected()){
                    tipo = 1;
                }
                boolean resul = ub.cadastrarUsuario(txtNome.getText(), txtCpf.getText(), tipo , txtEmail.getText(), txtSenha.getText());
                if(resul){
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
                    restaurarTela();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao tentar realizar o cadastro!\nO email requisitado pode ja ter sido cadastrado no sistema.", "Cadastro não efetuado", JOptionPane.ERROR_MESSAGE);
                }
                limparCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Preencha todos os campos para realizar o cadastro!", "Campos vazios", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            txtSenha.setText("");
            txtSenhaConfirm.setText("");
            JOptionPane.showMessageDialog(null, "As senhas são incompatíveis!", "Senhas incompatíveis", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void camposBuscado(){
        txtCpf.setEditable(false);
        txtEmail.setEditable(false);
        txtNome.setEditable(false);
        txtSenha.setEditable(false);
        txtSenhaConfirm.setEditable(false);
        rbAluno.setEnabled(false);
        rbProfessor.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnBuscar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnAtualizar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    
    private void limparCampos(){
        txtCpf.setText("");
        txtEmail.setText("");
        txtNome.setText("");
        txtSenha.setText("");
        txtSenhaConfirm.setText("");
        txtID.setText("");
        optGroupTipo.clearSelection();
    }
    
    private void camposNovo(){
        limparCampos();
        rbAluno.setEnabled(true);
        rbProfessor.setEnabled(true);
        txtCpf.setEditable(true);
        txtEmail.setEditable(true);
        txtNome.setEditable(true);
        txtSenha.setEditable(true);
        txtSenhaConfirm.setEditable(true);
        btnConfirmar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAtualizar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
        rbAluno.requestFocus();
        
    }
    
    private void restaurarTela(){
        limparCampos();
        rbAluno.setEnabled(false);
        rbProfessor.setEnabled(false);
        txtCpf.setEditable(false);
        txtEmail.setEditable(false);
        txtNome.setEditable(false);
        txtSenha.setEditable(false);
        txtSenhaConfirm.setEditable(false);
        btnBuscar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnConfirmar.setEnabled(false);
        btnAtualizar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        modo = null;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAtualizar;
    private java.awt.Button btnBuscar;
    private java.awt.Button btnCancelar;
    private java.awt.Button btnConfirmar;
    private java.awt.Button btnExcluir;
    private java.awt.Button btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup optGroupTipo;
    private javax.swing.JRadioButton rbAluno;
    private javax.swing.JRadioButton rbProfessor;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaConfirm;
    // End of variables declaration//GEN-END:variables
}
