/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import banco.Conexao;
import banco.EmprestimoBanco;
import banco.Sistema;
import java.net.URL;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.ItemBuscaEmprestimo;
import model.ItemBuscaExemplar;
import model.Usuario;

/**
 *
 * @author Marcelo Moreira
 */
public class TelaEmprestimo extends javax.swing.JFrame {
    private Principal parent;
    private String modo;
    private ItemBuscaExemplar item;
    private EmprestimoBanco eb;
    private Usuario usuario;
    private boolean autorizado;
    private ItemBuscaEmprestimo itemEmprestimo;
    /**
     * Creates new form TelaEmprestimo
     */
    public void setAutoridado(boolean auto){
        autorizado = auto;
        LocalDate hoje = LocalDate.now();
        LocalDate devolucaoEstimada = hoje.plusDays(31);
        String hojeStr = hoje.format(DateTimeFormatter.ISO_DATE);
        String dataDev = devolucaoEstimada.format(DateTimeFormatter.ISO_DATE);
        if(auto){
            boolean resul = eb.realizarEmprestimo(Integer.parseInt(txtIDExemplar.getText()), Integer.parseInt(txtIDUsuario.getText()), Integer.parseInt(txtIDBibliotecario.getText()), hojeStr, dataDev);
            if(resul){
                JOptionPane.showMessageDialog(null, "Empréstimo realizado com sucesso!\nData de devolução: "+devolucaoEstimada.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), "Empréstimo realizado", JOptionPane.INFORMATION_MESSAGE);
                restaurarTela();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao tentar realizar o empréstimo!\n"+hojeStr+dataDev, "Erro ao realizar o procedimento", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }
    
    public void setItemBuscaEmprestimo(ItemBuscaEmprestimo e){
        itemEmprestimo = e;
        txtCodBarras.setText(e.getCodBarras());
        txtDataEmprestimo.setText(e.getDataEmprestimo());
        txtIDBibliotecario.setText(String.valueOf(e.getIdBibliotecaria()));
        txtIDEmprestimo.setText(String.valueOf(e.getIdEmprestimo()));
        txtIDExemplar.setText(String.valueOf(e.getIdExemplar()));
        txtIDUsuario.setText(String.valueOf(e.getIdUsuario()));
        txtMulta.setText(String.valueOf(e.getMulta()));
        txtNomeUsuario.setText(e.getNomeUsuario());
        txtPrevisaoDevolucao.setText(e.getDataPrevistaDevol());
        if(e.getDataDevolucao().equals("11/11/1111")){
            txtDataDevolucao.setText("");
        }else{
            txtDataDevolucao.setText(e.getDataDevolucao());
        }
        txtRenovacoes.setText(String.valueOf(e.getQtdRenovacoes())+"/"+Sistema.getQtdRenovacoesPermitir());
        txtTitulo.setText(e.getTitulo());
        camposBuscado();
    }
    
    public void setUsuario(Usuario a){
        usuario = a;
        txtIDUsuario.setText(String.valueOf(a.getId()));
        txtNomeUsuario.setText(a.getNome());
    }
    
    public void setItemBuscaExemplar(ItemBuscaExemplar item){
        this.item = item;
        txtIDExemplar.setText(String.valueOf(item.getIdExemplar()));
        txtTitulo.setText(item.getTitulo());
    }
    
    private TelaEmprestimo() {
        initComponents();
    }
    
    public TelaEmprestimo(Principal parent){
        this();
        this.parent = parent;
        this.setIconImage(parent.getIconImage());
        URL url = this.getClass().getResource("images/lupa.png");
        Icon icon = new ImageIcon(url);
        btnBuscarExemplar.setIcon(icon);
        btnBuscarUsuario.setIcon(icon);
        eb = new EmprestimoBanco(Conexao.getConexao());
        restaurarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDExemplar = new javax.swing.JTextField();
        btnBuscarExemplar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDUsuario = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        txtIDBibliotecario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtIDEmprestimo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDevolver = new java.awt.Button();
        btnRenovar = new java.awt.Button();
        txtPrevisaoDevolucao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRenovacoes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JTextField();
        btnConfirmar = new java.awt.Button();
        btnNovo = new java.awt.Button();
        btnBuscar = new java.awt.Button();
        btnAtualizar = new java.awt.Button();
        btnExcluir = new java.awt.Button();
        btnCancelar = new java.awt.Button();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID Exemplar:");

        txtIDExemplar.setEnabled(false);
        txtIDExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDExemplarActionPerformed(evt);
            }
        });

        btnBuscarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarExemplarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Bibliotecario:");

        jLabel4.setText("ID Usuário:");

        txtIDUsuario.setEnabled(false);

        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        txtIDBibliotecario.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtIDEmprestimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIDEmprestimo.setEnabled(false);

        jLabel1.setText("ID Empréstimo:");

        btnDevolver.setLabel("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnRenovar.setLabel("Renovar");
        btnRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtIDEmprestimo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRenovar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(btnRenovar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtPrevisaoDevolucao.setEditable(false);

        jLabel7.setText("Previsão de Devolução:");

        txtDataEmprestimo.setEditable(false);

        jLabel6.setText("Data Empréstimo:");

        txtMulta.setEditable(false);

        jLabel8.setText("Multa:");

        txtRenovacoes.setEditable(false);

        jLabel5.setText("Renovações:");

        jLabel9.setText("Título:");

        txtTitulo.setEditable(false);

        jLabel10.setText("Nome Usuário:");

        txtNomeUsuario.setEditable(false);

        jLabel11.setText("Cód. Barras:");

        txtCodBarras.setEditable(false);

        jLabel12.setText("Data Devolução:");

        txtDataDevolucao.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNomeUsuario)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIDUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtIDExemplar))
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(btnBuscarExemplar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodBarras)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIDBibliotecario)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(txtRenovacoes, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(txtPrevisaoDevolucao)
                                .addComponent(jLabel12)
                                .addComponent(txtDataDevolucao)
                                .addComponent(txtMulta)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrevisaoDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRenovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel8))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscarExemplar, btnBuscarUsuario});

        btnConfirmar.setLabel("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnNovo.setLabel("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnBuscar.setLabel("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtualizar.setLabel("Atualizar");

        btnExcluir.setLabel("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAtualizar, btnBuscar, btnCancelar, btnConfirmar, btnExcluir, btnNovo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtualizar, btnBuscar, btnCancelar, btnConfirmar, btnExcluir, btnNovo});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDExemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDExemplarActionPerformed

    private void btnBuscarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarExemplarActionPerformed
        BuscaExemplar b = new BuscaExemplar(null, this);
        this.enable(false);
        b.setVisible(true);
    }//GEN-LAST:event_btnBuscarExemplarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.enable(true);
        restaurarTela();
    }//GEN-LAST:event_formWindowClosing

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        camposNovo();
        txtIDBibliotecario.setText(String.valueOf(parent.getBibliotecarialogada().getId()));
	LocalDate dateNow = LocalDate.now(); 
	txtDataEmprestimo.setText(dateNow.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        LocalDate dataPrevi = dateNow.plusDays(31);
        txtPrevisaoDevolucao.setText(dataPrevi.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtRenovacoes.setText("0/"+Sistema.getQtdRenovacoesPermitir());
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Realmente deseja cancelar?", "Cancelar Operação", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            restaurarTela();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        BuscaUsuario b = new BuscaUsuario(null, this);
        this.enable(false);
        b.setVisible(true);
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscaEmprestimo b = new BuscaEmprestimo(this);
        this.enable(false);
        b.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o empréstimo?\nTodos os dados referentes a ele serão excluídos do sistema.", "Excluir Empréstimo", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            excluir();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarActionPerformed
        String dat = itemEmprestimo.getDataPrevistaDevol();
        
        verificaAtraso(dat, "renovar");
    }//GEN-LAST:event_btnRenovarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        String dat = itemEmprestimo.getDataPrevistaDevol();
        
        verificaAtraso(dat, "devolver");
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void verificaAtraso(String data, String botao){
        int conf = JOptionPane.showConfirmDialog(null, "Realmente deseja "+botao+"?", "Cancelar Operação", JOptionPane.YES_NO_OPTION);
        if(conf == 0){
            String spl[] = data.split("/");
            LocalDate hoje = LocalDate.now();
            LocalDate previ = LocalDate.of(Integer.parseInt(spl[2]), Integer.parseInt(spl[1]), Integer.parseInt(spl[0]));
            int diasAtrasados = qtdDiasDiferenca(previ, hoje);
            if(diasAtrasados > 0){
                int a = JOptionPane.showConfirmDialog(null, "O exemplar está atrasado em "+diasAtrasados+" dias!\nMulta referente ao atraso(dia): R$"+Sistema.getValorMultaPorDia()+"\nMulta referente ao atraso(Total): R$"+(diasAtrasados*Sistema.getValorMultaPorDia())+"\nDeseja confirmar o recebimento deste valor?", "Confirmar recebimento do valor", JOptionPane.YES_NO_OPTION);
                if(a == 0){
                    if(botao.equals("renovar")){
                        renovar(itemEmprestimo.getMulta()+(Sistema.getValorMultaPorDia()*diasAtrasados));
                    }else if(botao.equals("devolver")){
                        devolver(itemEmprestimo.getMulta()+(Sistema.getValorMultaPorDia()*diasAtrasados));
                    }
                }
            }else{
                if(botao.equals("renovar")){
                    renovar(0);
                }else if(botao.equals("devolver")){
                    devolver(0);
                }
            }
        }
    }
    
    private void excluir(){
        boolean resu = eb.excluirEmprestimo(itemEmprestimo.getIdEmprestimo());
        if(resu){
            JOptionPane.showMessageDialog(null, "Empréstimo excluído com sucesso!", "Exclusão bem sucedida", JOptionPane.INFORMATION_MESSAGE);
            restaurarTela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao tentar excluir o empréstimo!", "Erro na exclusão", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void devolver(float valMulta){
        boolean resu = eb.devolverEmprestimo(itemEmprestimo.getIdEmprestimo(), valMulta, itemEmprestimo.getIdExemplar());
        if(resu){
            JOptionPane.showMessageDialog(null, "Exemplar devolvido com sucesso!", "Exemplar devolvido", JOptionPane.INFORMATION_MESSAGE);
            restaurarTela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao tentar devolver exemplar!", "Errao ao devolver exemplar", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void renovar(float valMulta){
        if((itemEmprestimo.getQtdRenovacoes()+1) <= 10){
            LocalDate hoje = LocalDate.now();
            boolean ret = eb.renovarEmprestimo(itemEmprestimo.getIdEmprestimo(), itemEmprestimo.getQtdRenovacoes()+1, valMulta);
            if(ret){
                restaurarTela();
                JOptionPane.showMessageDialog(null, "Renovação efetuada com sucesso!\nNova data de devolução: "+hoje.plusDays(31).format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), "Renovação efetuada", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(null, "Erro ao realizar a renovação!", "Erro ao tentar renovar", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Este exemplar já excedeu o numero máximo de renovações!", "Limite de renovações excedido", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private int qtdDiasDiferenca(LocalDate inicio, LocalDate fim){
        Period p = Period.between(inicio, fim);
        
        int total = (p.getYears()*365) + (p.getMonths()*31) + p.getDays();
        return total;
    }
    
    private void cadastrar(){
        if(!txtIDExemplar.getText().equals("") && !txtIDUsuario.getText().equals("")){
            TelaAutorizEmpr t = new TelaAutorizEmpr(this);
            this.enable(false);
            t.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os campos exemplar e o usuário!", "Campos vazios", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void camposNovo(){
        limparCampos();
        btnRenovar.setEnabled(false);
        btnDevolver.setEnabled(false);
        btnBuscarExemplar.setEnabled(true);
        btnBuscarUsuario.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnConfirmar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnAtualizar.setEnabled(false);
        btnExcluir.setEnabled(false); 
        modo = "novo";
    }
    
    private void camposBuscado(){
        btnAtualizar.setEnabled(false);
        
        btnNovo.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnConfirmar.setEnabled(false); 
        
        if(itemEmprestimo.getDataDevolucao().equals("11/11/1111")){
            btnDevolver.setEnabled(true);
            btnRenovar.setEnabled(true);
            btnExcluir.setEnabled(false);
        }else{
            btnDevolver.setEnabled(false);
            btnRenovar.setEnabled(false);
            btnExcluir.setEnabled(true);
        }
        
    }
    
    private void limparCampos(){
        txtDataEmprestimo.setText("");
        txtIDBibliotecario.setText("");
        txtIDEmprestimo.setText("");
        txtIDExemplar.setText("");
        txtIDUsuario.setText("");
        txtMulta.setText("");
        txtPrevisaoDevolucao.setText("");
        txtRenovacoes.setText("");
        txtTitulo.setText("");
        txtNomeUsuario.setText("");
        txtCodBarras.setText("");
        txtDataDevolucao.setText("");
        autorizado = false;
    }
    
    private void restaurarTela(){
        limparCampos();
        btnRenovar.setEnabled(false);
        btnDevolver.setEnabled(false);
        btnBuscarExemplar.setEnabled(false);
        btnBuscarUsuario.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAtualizar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnBuscar.setEnabled(true);
        
        modo = null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAtualizar;
    private java.awt.Button btnBuscar;
    private javax.swing.JButton btnBuscarExemplar;
    private javax.swing.JButton btnBuscarUsuario;
    private java.awt.Button btnCancelar;
    private java.awt.Button btnConfirmar;
    private java.awt.Button btnDevolver;
    private java.awt.Button btnExcluir;
    private java.awt.Button btnNovo;
    private java.awt.Button btnRenovar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtDataDevolucao;
    private javax.swing.JTextField txtDataEmprestimo;
    private javax.swing.JTextField txtIDBibliotecario;
    private javax.swing.JTextField txtIDEmprestimo;
    private javax.swing.JTextField txtIDExemplar;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtPrevisaoDevolucao;
    private javax.swing.JTextField txtRenovacoes;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
